#cloud-config
users:
  - name: CHANGE_USERNAME
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC9Bkz8h8fhJI9C3Watz22bykuccYpKaBMrGjBt8A8zRvlYqJS+MSc+/uY6krujyBsuELhkCdO/NH5slDNfGLu9NKKdIJcwCm55NqGGfMFCbKn4OdqZFyOWDMk4kydj5ohMNGQV1lgMDdwIWVAasjVh0Td5Zbk3F966H5WssFntbgvoZcAMwpZdiQkZuc2Wbnj6CMzj+Y0hnhSJdD9JrXlKIJZuKC5ZxFElyo9wPbQPy7SUebe3Gr/rNrBTYIXxqIqORxmuxqQj4sVunkXlqKJKuPVOHg5xrB1WJ4E1tz5vWFApe2s1aWvYs/BXUHlKLa/uyJiNAn008okhgCyEY8z7
    ssh_import_id: CHANGE_LAUNCHPAD_ID
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: [root,sudo,staff]
    shell: /bin/bash
disable_root: false
network:
  version: 2
  config:
  - type: physical
    name: eth0
    subnets:
      - type: dhcp
proxy: CHANGE_PROXY
http_proxy: CHANGE_HTTP_PROXY
https_proxy: CHANGE_HTTPS_PROXY
ftp_proxy: CHANGE_FTP_PROXY
runcmd:
  - snap install --classic --edge git-ubuntu
  - systemctl stop unattended-upgrades
  - systemctl stop systemd-remount-fs
  - system reset-failed
  - passwd -d root
  - passwd -d CHANGE_USERNAME
  - echo "debconf debconf/priority select low" | sudo debconf-set-selections
  - DEBIAN_FRONTEND=noninteractive dpkg-reconfigure debconf
  - DEBIAN_FRONTEND=noninteractive apt-get update -y || true
  - DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y || true
  - DEBIAN_FRONTEND=noninteractive apt-get autoremove -y || true
  - DEBIAN_FRONTEND=noninteractive apt-get autoclean -y || true
  - DEBIAN_FRONTEND=noninteractive apt-get install -y openjdk-8-jdk || true
  - systemctl disable systemd-remount-fs
  - systemctl disable --now unattended-upgrades
  - systemctl disable --now apt-daily-upgrade.timer
  - systemctl disable --now apt-daily.timer
  - systemctl disable --now accounts-daemon.service
  - systemctl disable --now motd-news.timer
  - systemctl disable --now irqbalance.service
  - systemctl disable --now rsync.service
  - systemctl disable --now ebtables.service
  - systemctl disable --now pollinate.service
  - systemctl disable --now ufw.service
  - systemctl disable --now apparmor.service
  - systemctl disable --now apport-autoreport.path
  - systemctl disable --now apport-forward.socket
  - systemctl disable --now iscsi.service
  - systemctl disable --now open-iscsi.service
  - systemctl disable --now iscsid.socket
  - systemctl disable --now multipathd.socket
  - systemctl disable --now multipath-tools.service
  - systemctl disable --now multipathd.service
  - systemctl disable --now lvm2-monitor.service
  - systemctl disable --now lvm2-lvmpolld.socket
  - systemctl disable --now lvm2-lvmetad.socket
  - systemctl disable --now fstrim.timer
  - systemctl disable --now e2scrub_all.timer
  - systemctl disable --now e2scrub_reap.service
  - systemctl disable --now dbus-org.freedesktop.thermald.service
  - systemctl enable --now serial-getty@hvc0.service
  - systemctl enable --now serial-getty@hvc1.service
  - systemctl enable --now serial-getty@hvc2.service
  - systemctl enable --now serial-getty@hvc3.service
  - systemctl enable --now serial-getty@hvc4.service
  - systemctl enable --now serial-getty@hvc5.service
  - DEBIAN_FRONTEND=noninteractive apt-get install -y haveged || true
  - rm -rf /root/.bashrc /root/.gnupg /root/.profile /root/.ssh/
  - cp -rfp /home/CHANGE_USERNAME/.ssh /root/.ssh
  - chown -R root:root /root/.ssh
  - ln -s /home/CHANGE_USERNAME/.bashrc /root/.bashrc
  - ln -s /home/CHANGE_USERNAME/.vimrc /root/.vimrc
  - ln -s /home/CHANGE_USERNAME/.viminfo /root/.viminfo
  - ln -s /home/CHANGE_USERNAME/.vim /root/.vim
  - ln -s /home/CHANGE_USERNAME/.alias /root/.alias
  - ln -s /home/CHANGE_USERNAME/.bash_profile /root/.bash_profile
  - ln -s /home/CHANGE_USERNAME/.profile /root/.profile
  - ln -s /home/CHANGE_USERNAME/.gnupg /root/.gnupg
  - mkdir -p /etc/systemd/system/serial-getty@hvc0.service.d
  - mkdir -p /etc/systemd/system/serial-getty@hvc1.service.d
  - mkdir -p /etc/systemd/system/serial-getty@hvc2.service.d
  - mkdir -p /etc/systemd/system/serial-getty@hvc3.service.d
  - mkdir -p /etc/systemd/system/serial-getty@hvc4.service.d
  - mkdir -p /etc/systemd/system/serial-getty@hvc5.service.d
packages:
  - man
  - manpages
  - hello
  - locales
  - less
  - vim
  - jq
  - uuid
  - bash-completion
  - sudo
  - rsync
  - bridge-utils
  - net-tools
  - vlan
  - ncurses-term
  - iputils-arping
  - iputils-ping
  - iputils-tracepath
  - traceroute
  - mtr-tiny
  - tcpdump
  - dnsutils
  - ssh-import-id
  - openssh-server
  - openssh-client
  - software-properties-common
  - build-essential
  - devscripts
  - git-buildpackage
  - ubuntu-dev-tools
  - linux-headers-generic
  - gdb
  - strace
  - ltrace
  - lsof
  - xterm
  - vim-gtk
  - vim-nox
  - gtk2-engines
  - gtk2-engines-murrine
  - gtk2-engines-pixbuf
  - gtk3-engines-breeze
  - gtk3-engines-unico
  - dmz-cursor-theme
  - gnome-icon-theme
  - gnome-themes-standard
  - gnome-themes-ubuntu
  - gtk-3-examples
  - keychain
power_state:
  delay: 'now'
  mode: reboot
  timeout: 10
  condition: True
final_message: "The system is finally up! Enjoy!"
write_files:
  - path: /etc/ssh/sshd_config
    content: |
      Port 22
      AddressFamily any
      SyslogFacility AUTH
      LogLevel INFO
      PermitRootLogin yes
      PubkeyAuthentication yes
      PasswordAuthentication yes
      ChallengeResponseAuthentication no
      GSSAPIAuthentication no
      HostbasedAuthentication no
      PermitEmptyPasswords no
      UsePAM yes
      IgnoreUserKnownHosts yes
      IgnoreRhosts yes
      X11Forwarding yes
      X11DisplayOffset 10
      X11UseLocalhost yes
      PermitTTY yes
      PrintMotd no
      TCPKeepAlive yes
      PermitTunnel yes
      ClientAliveInterval 5
      Banner none
      AcceptEnv LANG LC_* EDITOR PAGER SYSTEMD_EDITOR
      Subsystem	sftp /usr/lib/openssh/sftp-server
  - path: /etc/ssh/ssh_config
    content: |
      Host *
        ForwardAgent no
        ForwardX11 no
        PasswordAuthentication yes
        CheckHostIP no
        AddressFamily any
        SendEnv LANG LC_* EDITOR PAGER
        StrictHostKeyChecking no
        HashKnownHosts yes
        ServerAliveInterval 5
  - path: /etc/sudoers
    content: |
        Defaults env_keep += "LANG LANGUAGE LINGUAS LC_* _XKB_CHARSET"
        Defaults env_keep += "HOME EDITOR SYSTEMD_EDITOR PAGER"
        Defaults env_keep += "XMODIFIERS GTK_IM_MODULE QT_IM_MODULE QT_IM_SWITCHER"
        Defaults env_keep += "HTTP_PROXY HTTPS_PROXY FTP_PROXY"
        Defaults env_keep += "http_proxy https_proxy ftp_proxy"
        Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        Defaults logfile=/var/log/sudo.log,loglinelen=0
        Defaults !syslog, !pam_session
        root ALL=(ALL) NOPASSWD: ALL
        %wheel ALL=(ALL) NOPASSWD: ALL
        %sudo ALL=(ALL) NOPASSWD: ALL
        CHANGE_USERNAME ALL=(ALL) NOPASSWD: ALL
  - path: /etc/default/grub
    content: |
        GRUB_DEFAULT=0
        GRUB_HIDDEN_TIMEOUT_QUIET=false
        GRUB_TIMEOUT=2
        GRUB_DISTRIBUTOR=""
        # ttyS0 only for GRUB (virtio-serial won't cause vm exits)
        GRUB_CMDLINE_LINUX_DEFAULT="root=/dev/vda2 console=hvc0 console=tty0 apparmor=0 net.ifnames=0 elevator=noop pti=off kpti=off nopcid noibrs noibpb spectre_v2=off nospec_store_bypass_disable l1tf=off nomodeset"
        GRUB_CMDLINE_LINUX=""
        GRUB_TERMINAL=serial
        GRUB_SERIAL_COMMAND="serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1"
        GRUB_DISABLE_LINUX_UUID="true"
        GRUB_DISABLE_RECOVERY="true"
        GRUB_DISABLE_OS_PROBER="true"
  - path: /etc/modules
    content: |
      virtio_balloon
      virtio_blk
      virtio_net
      virtio_pci
      virtio_ring
      virtio
      ext4
  - path: /etc/initramfs-tools/modules
    content: |
      virtio_balloon
      virtio_blk
      virtio_net
      virtio_pci
      virtio_ring
      virtio
      ext4
  - path: /etc/systemd/system/serial-getty@hvc0.service.d/override.conf
    content: |
        [Service]
        User=CHANGE_USERNAME
        Environment=HOME=/home/CHANGE_USERNAME
        WorkingDirectory=/home/CHANGE_USERNAME
        ExecStart=
        ExecStart=-/bin/bash
        StandardInput=tty
        StandardOutput=tty
        Restart=always
        [Install]
        WantedBy=getty.target
  - path: /etc/systemd/system/serial-getty@hvc1.service.d/override.conf
    content: |
        [Service]
        User=CHANGE_USERNAME
        Environment=HOME=/home/CHANGE_USERNAME
        WorkingDirectory=/home/CHANGE_USERNAME
        ExecStart=
        ExecStart=-/bin/bash
        StandardInput=tty
        StandardOutput=tty
        Restart=always
        [Install]
        WantedBy=getty.target
  - path: /etc/systemd/system/serial-getty@hvc2.service.d/override.conf
    content: |
        [Service]
        User=CHANGE_USERNAME
        Environment=HOME=/home/CHANGE_USERNAME
        WorkingDirectory=/home/CHANGE_USERNAME
        ExecStart=
        ExecStart=-/bin/bash
        StandardInput=tty
        StandardOutput=tty
        Restart=always
        [Install]
        WantedBy=getty.target
  - path: /etc/systemd/system/serial-getty@hvc3.service.d/override.conf
    content: |
        [Service]
        User=CHANGE_USERNAME
        Environment=HOME=/home/CHANGE_USERNAME
        WorkingDirectory=/home/CHANGE_USERNAME
        ExecStart=
        ExecStart=-/bin/bash
        StandardInput=tty
        StandardOutput=tty
        Restart=always
        [Install]
        WantedBy=getty.target
  - path: /etc/systemd/system/serial-getty@hvc4.service.d/override.conf
    content: |
        [Service]
        User=CHANGE_USERNAME
        Environment=HOME=/home/CHANGE_USERNAME
        WorkingDirectory=/home/CHANGE_USERNAME
        ExecStart=
        ExecStart=-/bin/bash
        StandardInput=tty
        StandardOutput=tty
        Restart=always
        [Install]
        WantedBy=getty.target
  - path: /etc/systemd/system/serial-getty@hvc5.service.d/override.conf
    content: |
        [Service]
        User=CHANGE_USERNAME
        Environment=HOME=/home/CHANGE_USERNAME
        WorkingDirectory=/home/CHANGE_USERNAME
        ExecStart=
        ExecStart=-/bin/bash
        StandardInput=tty
        StandardOutput=tty
        Restart=always
        [Install]
        WantedBy=getty.target
  - path: /etc/systemd/system/serial-getty@hvc6.service.d/override.conf
    content: |
        [Service]
        User=CHANGE_USERNAME
        Environment=HOME=/home/CHANGE_USERNAME
        WorkingDirectory=/home/CHANGE_USERNAME
        ExecStart=
        ExecStart=-/bin/bash
        StandardInput=tty
        StandardOutput=tty
        Restart=always
        [Install]
        WantedBy=getty.target
apt:
  preserve_sources_list: false
  primary:
    - arches: [default]
      uri: CHANGE_REPOSITORY
  sources_list: |
    deb $MIRROR $RELEASE main restricted universe multiverse
    deb $MIRROR $RELEASE-updates main restricted universe multiverse
    deb $MIRROR $RELEASE-proposed main restricted universe multiverse
    deb-src $MIRROR $RELEASE main restricted universe multiverse
    deb-src $MIRROR $RELEASE-updates main restricted universe multiverse
    deb-src $MIRROR $RELEASE-proposed main restricted universe multiverse
  conf: |
    Acquire::http::Proxy "CHANGE_PROXY";
    Dpkg::Options {
      "--force-confdef";
      "--force-confold";
    };
  sources:
    debug.list:
      source: |
        deb http://ddebs.ubuntu.com $RELEASE main restricted universe multiverse
        deb http://ddebs.ubuntu.com $RELEASE-updates main restricted universe multiverse
        deb http://ddebs.ubuntu.com $RELEASE-proposed main restricted universe multiverse
      keyid: C8CAB6595FDFF622
